namespace := "skyramp"

create-namespace:
    kubectl create namespace {{namespace}} || echo "Namespace {{namespace}} already exists"


install-opentsdb:
    helm install -n {{ namespace }} opentsdb .
