# Default values for OpenTSDB
replicaCount: 1

image:
  repository: petergrace/opentsdb-docker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4242

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Additional environment variables
env: []