image:
  repository: mongo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "6.0.6"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
name: ""

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 27017

mongodb:
  auth:
    username: ""
    password: ""
    database: "dashboarddb"
  
operator: 
  enabled: true