apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opentsdb.fullname" . }}
  labels:
    {{- include "opentsdb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opentsdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opentsdb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4242
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data/hbase
      volumes:
        - name: data
          emptyDir: {}