apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skyramp-mocker.fullname" . }}
  labels:
    {{- include "skyramp-mocker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "skyramp-mocker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "skyramp-mocker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "skyramp-mocker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Chart.Name }}
          configMap:
            name: {{ include "skyramp-mocker.fullname" . }}
        - name: {{ include "skyramp-mocker.userGrpcFilesConfigMapName" . }}
          configMap:
            name: {{ include "skyramp-mocker.userGrpcFilesConfigMapName" . }}
        - name: {{ include "skyramp-mocker.userThriftFilesConfigMapName" . }}
          configMap:
            name: {{ include "skyramp-mocker.userThriftFilesConfigMapName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Chart.Name }}
              mountPath: {{ .Values.bootConfig.mountPath }}
            - name: {{ include "skyramp-mocker.userGrpcFilesConfigMapName" . }}
              mountPath: {{ include "skyramp-mocker.userGrpcFilesMountPath" . }}
            - name: {{ include "skyramp-mocker.userThriftFilesConfigMapName" . }}
              mountPath: {{ include "skyramp-mocker.userThriftFilesMountPath" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
                # livenessProbe:
                #   httpGet:
                #     path: /
                #     port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.bootConfig.config.managementPort }} 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
