{{- if .Values.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "worker.clusterRoleName" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
{{- end }}
