{{- if .Values.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "worker.clusterRoleName" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "worker.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "worker.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
