apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.userGrpcFilesConfigMapName" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
immutable: false
data: null
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.userThriftFilesConfigMapName" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
immutable: false
data: null