apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.rbac }}
  kind: Role
  name: {{ include "worker.fullname" . }}
{{- else }}
  kind: ClusterRole
  name: edit 
{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "worker.serviceAccountName" . }}