apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "worker.bootConfig" . | nindent 4 }}
  resources.yaml: "" 
  schemaConfig.yaml: ""
immutable: false