apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- toYaml .Values.persistence.hostPath.volume | nindent 8 }}
        - name: {{ .Chart.Name }}
          configMap:
            name: {{ include "worker.fullname" . }}
        - name: {{ include "worker.userGrpcFilesConfigMapName" . }}
          configMap:
            name: {{ include "worker.userGrpcFilesConfigMapName" . }}
        - name: {{ include "worker.userThriftFilesConfigMapName" . }}
          configMap:
            name: {{ include "worker.userThriftFilesConfigMapName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            {{- toYaml .Values.command | nindent 12 }}
          env:
          - name: CGO_ENABLED
            value: "1"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            {{- toYaml .Values.persistence.hostPath.volumeMount | nindent 12 }}
            - name: {{ .Chart.Name }}
              mountPath: {{ .Values.bootConfig.mountPath }}
            - name: {{ include "worker.userGrpcFilesConfigMapName" . }}
              mountPath: {{ include "worker.userGrpcFilesMountPath" . }}
            - name: {{ include "worker.userThriftFilesConfigMapName" . }}
              mountPath: {{ include "worker.userThriftFilesMountPath" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
                # livenessProbe:
                #   httpGet:
                #     path: /
                #     port: http
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
