apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-server.fullname" . }}-frontend
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          # env:
          #   - name: NODE_ENV
          #     value: production
          ports:
            - containerPort: 3000
