{{- if not .Values.operator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-datastore.fullname" . }}-svc
  labels: 
    {{- include "mongo-datastore.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  clusterIP: None
  selector:
    {{- include "mongo-datastore.selectorLabels" . | nindent 6 }}
{{- end }}