name: Chart Test on Push

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run chart-testing
        working-directory: charts
        run: helm lint worker --values worker/values.yaml
