name: Release Charts

on:
  workflow_dispatch: null
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
      
      - name: Install Dep Charts
        run: |
          helm repo add mongodb https://mongodb.github.io/helm-charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ github.token }}"
        with:
          version: v1.5.0
          charts_dir: charts
          release_name_template: ${{ github.repository }}-{{ .Chart.Name }}-{{ .Chart.Version }}
          create_gh_pages: false
